import {describe,it,expect} from "vitest";
import {calculateEligibility,safeUrl,quoteIsPresent,type EligibilityInput} from "./lib/eligibility";
const base:EligibilityInput={purchasePrice:449,currentPrice:399,currency:"USD",currentCurrency:"USD",quantity:1,purchaseDate:"2026-09-17",windowDays:14,adjustmentsAllowed:true,modelEligible:true,confidence:.91,sameProduct:true,evidenceVerified:true,now:Date.parse("2026-09-22T12:00:00Z")};
describe("evidence-based recovery",()=>{
 it.each([{quantity:1.5},{confidence:1.1},{windowDays:-1},{windowDays:1.5},{purchaseDate:"2026-02-31"}])("rejects malformed inputs: %j",change=>expect(calculateEligibility({...base,...change})).toMatchObject({eligible:false,amount:0}));
 it("returns exactly $50 for the supported golden path",()=>expect(calculateEligibility(base)).toMatchObject({eligible:true,amount:50}));
 it.each([{currentPrice:449},{currentPrice:460},{currentCurrency:"EUR"},{windowDays:null},{adjustmentsAllowed:false},{modelEligible:false},{confidence:.8},{sameProduct:false},{evidenceVerified:false},{purchaseDate:"2026-09-25"},{purchaseDate:"bad"},{purchasePrice:NaN},{currentPrice:Infinity},{quantity:-1}])("does not show unsupported money: %j",change=>expect(calculateEligibility({...base,...change})).toMatchObject({eligible:false,amount:0}));
 it("rejects expired claims",()=>expect(calculateEligibility({...base,purchaseDate:"2026-08-01"})).toMatchObject({eligible:false,expired:true}));
 it("uses cents and quantity without floating point residue",()=>expect(calculateEligibility({...base,purchasePrice:19.99,currentPrice:15.49,quantity:3}).amount).toBe(13.5));
 it("requires verbatim evidence",()=>{expect(quoteIsPresent("Within 14 days of purchase","Policy: within 14 days\n of purchase.")).toBe(true);expect(quoteIsPresent("Within 30 days of purchase","within 14 days of purchase")).toBe(false);});
 it.each(["http://store.com","https://127.0.0.1","https://localhost","https://169.254.169.254","https://user:pass@store.com","https://[::1]","https://store.com:9000"])("rejects unsafe source %s",url=>expect(()=>safeUrl(url)).toThrow());
});
it("matches verbatim quotes through markdown links, trademarks and smart quotes",()=>{const page="We’ll match the price if you find it for less at [Target.com](https://www.target.com), in Target stores or with a Target Circle™ deal.";expect(quoteIsPresent("We'll match the price if you find it for less at Target.com, in Target stores or with a Target Circle deal.",page)).toBe(true);expect(quoteIsPresent("We refund any competitor price difference forever.",page)).toBe(false);});
it("verifies quotes joined across list items sentence by sentence",()=>{const page="Target Circle member).\n- Price matches may be requested within 14 days after purchase.\n- Original receipts are required for price adjustments.";expect(quoteIsPresent("Price matches may be requested within 14 days after purchase. Original receipts are required for price adjustments.",page)).toBe(true);expect(quoteIsPresent("Price matches may be requested within 30 days after purchase.",page)).toBe(false);});
