import {convexTest} from "convex-test";
import rateLimiterTest from "@convex-dev/rate-limiter/test";
import {expect,it} from "vitest";
import schema from "./schema";
import {api,internal} from "./_generated/api";
import type {Id} from "./_generated/dataModel";
import {CATALOG} from "./catalog";
const modules=import.meta.glob("./**/*.ts");
async function setup(){const t=convexTest(schema,modules);rateLimiterTest.register(t);const owner=await t.run(ctx=>ctx.db.insert("users",{isAnonymous:true}));const other=await t.run(ctx=>ctx.db.insert("users",{isAnonymous:true}));return {t,owner,other,a:t.withIdentity({subject:`${owner}|session`}),b:t.withIdentity({subject:`${other}|session`})};}
type T=Awaited<ReturnType<typeof setup>>["t"];
async function addClaim(t:T,purchaseId:Id<"purchases">,userId:Id<"users">){return t.run(async ctx=>{await ctx.db.patch(purchaseId,{status:"Eligible",potentialRecovery:25});return ctx.db.insert("claims",{purchaseId,userId,status:"Eligible",requestedAmount:25,recoveredAmount:0,recipient:"",draftSubject:"Price adjustment request",draftBody:"Please review."});});}
it("isolates private purchases and seeds idempotently",async()=>{const {a,b}=await setup();await a.mutation(api.purchases.seed,{});await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});expect(d.purchases.length).toBe(CATALOG.length);expect((await b.query(api.purchases.dashboard,{})).purchases).toHaveLength(0);await expect(b.query(api.purchases.detail,{id:d.purchases[0]._id})).rejects.toThrow("Purchase not found");await expect(b.mutation(api.purchases.setUrls,{id:d.purchases[0]._id,productUrl:"https://store.com/p",policyUrl:"https://store.com/policy"})).rejects.toThrow("Purchase not found");});
it("seeds real product and policy links, labelled as samples",async()=>{const {a}=await setup();await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});for(const p of d.purchases){expect(p.isDemo).toBe(true);expect(p.productUrl).toMatch(/^https:\/\/www\.target\.com\/p\//);expect(p.policyUrl).toMatch(/^https:\/\/www\.target\.com\/help\//);}});
it("replaces old fictional samples when the seed version changes",async()=>{const {t,owner,a}=await setup();await t.run(async ctx=>{await ctx.db.insert("profiles",{userId:owner,seeded:true,createdAt:Date.now()});await ctx.db.insert("purchases",{userId:owner,merchant:"Nova Electronics",productName:"Old sample",orderNumber:"DEMO-1",purchasePrice:10,currency:"USD",purchaseDate:"2026-09-01",productUrl:"",merchantWebsite:"",buyerEmail:"",quantity:1,policyUrl:"",potentialRecovery:0,status:"Monitoring",category:"package",isDemo:true,confirmed:true,createdAt:1,updatedAt:1});});await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});expect(d.purchases.some((p:{merchant:string})=>p.merchant==="Nova Electronics")).toBe(false);expect(d.purchases).toHaveLength(CATALOG.length);});
it("pushes a verified live price to watching samples only",async()=>{const {t,owner,a}=await setup();await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});const sony=d.purchases.find((p:{catalogSlug?:string})=>p.catalogSlug==="sony-wh1000xm5")!;const pods=d.purchases.find((p:{catalogSlug?:string})=>p.catalogSlug==="airpods-pro-2")!;await addClaim(t,pods._id,owner);await t.mutation(internal.catalog.record,{slug:"sony-wh1000xm5",price:299.99,priceQuote:"$299.99"});await t.mutation(internal.catalog.record,{slug:"airpods-pro-2",price:199.99,priceQuote:"$199.99"});const s=(await a.query(api.purchases.detail,{id:sony._id})).purchase;expect(s.currentPrice).toBe(299.99);expect(s.status).toBe("Price Drop");const p=(await a.query(api.purchases.detail,{id:pods._id})).purchase;expect(p.status).toBe("Eligible");expect(p.currentPrice).toBeUndefined();});
it("blocks unauthenticated reads",async()=>{const {t}=await setup();await expect(t.query(api.purchases.dashboard,{})).rejects.toThrow("private session");});
it("never emails a sample purchase",async()=>{const {a}=await setup();await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});await expect(a.mutation(api.claims.approve,{purchaseId:d.purchases[0]._id,confirmed:true})).rejects.toThrow("Demo purchases cannot");});
it("requires explicit approval and invalidates old evidence after URLs change",async()=>{const {t,owner,a}=await setup();await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});const p=d.purchases[0];await addClaim(t,p._id,owner);await expect(a.mutation(api.claims.approve,{purchaseId:p._id,confirmed:false})).rejects.toThrow("Explicit approval");await a.mutation(api.purchases.setUrls,{id:p._id,productUrl:"https://store.com/p",policyUrl:"https://store.com/policy"});const detail=await a.query(api.purchases.detail,{id:p._id});expect(detail.purchase.potentialRecovery).toBe(0);expect(detail.claim?.status).toBe("Needs Review");});
it("deduplicates provider delivery persistence",async()=>{const {t,owner,a}=await setup();await a.mutation(api.purchases.seed,{});const d=await a.query(api.purchases.dashboard,{});const claimId=await addClaim(t,d.purchases[0]._id,owner);await t.run(ctx=>ctx.db.patch(claimId,{sendAttemptId:"attempt"}));const payload={claimId,attemptId:"attempt",messageId:"message-test",threadId:"thread-test",sender:"test-inbox"};await t.mutation(internal.claims.sent,payload);await t.mutation(internal.claims.sent,payload);const detail=await a.query(api.purchases.detail,{id:d.purchases[0]._id});expect(detail.emails).toHaveLength(1);});
